{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nova.serviceAccountName" . }}
  labels:
{{ include "nova.labels" . | nindent 4 }}
{{- end -}}